services:
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"    
        volumes:
            - ./provisioning:/etc/grafana/provisioning
            - ${HOME}/.aws:/usr/share/grafana/.aws

        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - overlay                

networks:
    overlay:

